# Generated by Django 4.1.7 on 2023-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=200)),
                ('problem_desc', models.CharField(max_length=500)),
                ('problem_img', models.ImageField(blank=True, upload_to='problem_img')),
                ('problem_id', models.IntegerField(default=0)),
            ],
        ),
    ]
