# Generated by Django 4.1.5 on 2023-03-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problems',
        ),
    ]
