# Generated by Django 4.1.5 on 2023-03-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='ProblemStatement',
        ),
    ]
