# Generated by Django 4.1.5 on 2023-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0004_rename_problems_problemstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
