# Generated by Django 4.1.7 on 2023-03-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0005_problemcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemcomments',
            name='comment',
        ),
        migrations.AddField(
            model_name='problemcomments',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problemcomments',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nation_book.problemstatement'),
        ),
    ]
