# Generated by Django 4.1.7 on 2023-03-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0006_remove_problemcomments_comment_problemcomments_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_comments', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='problem_comments', to='nation_book.problemstatement')),
            ],
        ),
    ]
