# Generated by Django 4.1.7 on 2023-03-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0008_problemcomments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcomments',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problemcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nation_book.problemstatement'),
        ),
    ]
