# Generated by Django 4.1.7 on 2023-04-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0009_alter_problemcomments_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nation_book.problemstatement')),
            ],
        ),
        migrations.DeleteModel(
            name='Problems',
        ),
    ]
