# Generated by Django 4.1.7 on 2023-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0011_alter_smallproblems_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallproblems',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
