# Generated by Django 4.1.7 on 2023-04-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0012_alter_smallproblems_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smallproblems',
            options={'ordering': ['-time']},
        ),
    ]
