# Generated by Django 4.1.7 on 2023-04-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation_book', '0013_alter_smallproblems_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemcomments',
            options={'ordering': ['-time']},
        ),
    ]
